### ISSUE TITLE
Mission requirements probably need a scale back

### ISSUE THREAD

**Issue by edvordo** [galaxyofdrones/galaxyofdrones#16]
Loving the new mission system so far. But ..

The max per mission probably needs to be lowered by couple percentages or mining rate needs to increase.

I just got a mission for 1.1m Cobalt. Even with the planets I own that produce Cobalt, I would be unable to complete that mission. I can only generate around 870k Cobalt in the time that mission expires.

Yes, I know, I can just occupy more planets. But I think that would only move the problem by couple of days. Not to mention, the more rare planets take quite a while to get to (at the point where I am I'm talking about 3+ hours to get to planets Adamantine) and transport resources from them to the mothership, even with the buffs from Trading center lowering the transport time (which doesn't solve the issue).

I see three possible solutions:
 * lower the maximum percentage of all planets capacities to generate mission requirement
 * buff mining rate ( helps with generating resources )
 * allow for more motherships ( so that we can lower the travel time )

This looks good, but all the lines going out of screen (some double the length visible) are Adamantine (pink) or Thorium (black) producing planets, the two rarest materials in the galaxy :)

 ![transport](https://user-images.githubusercontent.com/6738779/35450449-5a567d8e-02c0-11e8-9878-f3c568175a43.png) )

**Comment by edvordo** [comment]
I by *lower* I meant like by couple of percentages, [not burn it to the ground](https://github.com/galaxyofdrones/galaxyofdrones/commit/8ad58a7bd8d9d4327c4b06c55f8d00ec62fab8c3#diff-d104ccd3a119f3034b4c150056f152ecR50) ![image](https://user-images.githubusercontent.com/6738779/36952002-6fc80eaa-200a-11e8-97f7-65ce49d3bfd1.png)

Unless the new missions and expeditions are going to have same/similar rewards, [this was a pretty hard nerf](https://user-images.githubusercontent.com/6738779/36952080-55322ee4-200b-11e8-8430-7bb72a42b422.png).

**Comment by petaki** [comment]
@edvordo Yes, it seems a radical change, but the progress is too fast and the expeditions will add similar xp reward.

But, I partially agree, because it makes easier. I will increment the capacity values back to 20%-60%.

**Comment by edvordo** [comment]
If you consider the progress too fast, I accept the change without complaint. Balancing isn't easy. I can always double the planet count I own already :D
