### ISSUE TITLE
Battle at occupied planet

### ISSUE THREAD

**Issue by isUndefined** [galaxyofdrones/galaxyofdrones#19]
Found a bug. I can attack new occupied planet. 
See my Battle logs
![3](https://user-images.githubusercontent.com/2869813/36255596-57e62354-1258-11e8-8caf-85f267ab3a7e.PNG)

Send Helios to new planet after some time send other Helios. 
![1](https://user-images.githubusercontent.com/2869813/36256157-635356d8-125a-11e8-9dae-7274d07d685b.PNG)

When planet will be occupied start construct buildings. After arrival second Helios in logs will show that he was attacker.

![2](https://user-images.githubusercontent.com/2869813/36256156-6331a600-125a-11e8-8f0f-743b92261e45.PNG)

**Comment by petaki** [comment]
Thank you for your report, [Fixed](https://github.com/galaxyofdrones/galaxyofdrones/commit/7ced8e48dde5b524d8154b8dd798288fab6341ac).

**Comment by edvordo** [comment]
![image](https://user-images.githubusercontent.com/6738779/36350956-ddd265d6-14a1-11e8-9ad6-fd01b544692f.png)
May not be fixed. I've sent those around 10 to 11 hours ago.

**Comment by petaki** [comment]
@edvordo Thanks, I fixed the backend, but I didn't test this UI glitch.

**Comment by petaki** [comment]
I deleted the stuck records, because I can't reproduce this, after the patch. Can you help me to re-test?

**Comment by edvordo** [comment]
Just sent 2 Helios class ships to one planet. Will know the result in a bit over an hour.

**Comment by petaki** [comment]
Yes, I tried, but the result:

- The first ship occupied the planet
- The second ship turned back

**Comment by edvordo** [comment]
Likewise. Not sure how I managed to make it produce that output.

**Comment by petaki** [comment]
Thanks for the help, I closed
