### ISSUE TITLE
No new missions

### ISSUE THREAD

**Issue by edvordo** [galaxyofdrones/galaxyofdrones#20]
I only just noticed, but I don't seem to be getting new missions. Last mission I have ends in 46 hours, which means there wasn't a mission added for 26 hours now.

![image](https://user-images.githubusercontent.com/6738779/36355580-96aeae78-14e5-11e8-8a4a-7f7d1980d4d9.png)

And no, I haven't completed the missions after the last one I mentioned, I certainly would not have enough resources for that.

**Comment by petaki** [comment]
Thanks for the report, [Fixed](https://github.com/galaxyofdrones/galaxyofdrones/commit/b365219bf11f224018757c44af68ba57d920a681)
