### ISSUE TITLE
Cannot turn in expedition

### ISSUE THREAD

**Issue by edvordo** [galaxyofdrones/galaxyofdrones#22]
For some reason, when I tried to turn in expedition 5918, the server always responded with 500.

I did have the required amount of Icarus class ships (74.87k), because I tried to turn in another one (4507, which required 77.76k), to test whether all of them are broken, and that one turned in okay.

I'm not sure, but I think I should have enough drones to test again before it expires. Unless you find what could have been wrong with it.

**Comment by petaki** [comment]
Thanks, [Fixed](https://github.com/galaxyofdrones/galaxyofdrones/commit/5a8842f56c6a81dd9c5b61d36975665b9f453c0c)
