### ISSUE TITLE
Game should warn you and/or log you out when session is expired

### ISSUE THREAD

**Issue by evan1024** [galaxyofdrones/galaxyofdrones#23]
Ran into this testing the game today. After leaving it idle for a long time, the ajax calls fails and returns an "Unauthorized" message that is not picked up by the frontend and will leave users confused as to why their actions are not working.

**Comment by edvordo** [comment]
Already mentioned here [#363110958](https://github.com/galaxyofdrones/galaxyofdrones/issues/17#issuecomment-363110958) :)

**Comment by petaki** [comment]
@evan1024 @edvordo Thank you for your suggestions! I will prioritize the global JS error handling.
