### ISSUE TITLE
Serious issue with online version

### ISSUE THREAD

**Issue by dfafefadfe** [galaxyofdrones/galaxyofdrones#24]
Hello, I played the online version of the game and it seems to have serious issue with its security. There is a guy with username filler, he attacked my planet and destroyed it, I created another account and it was far away from his planet, and then he attacked it again, same thing happened again 3rd time, so either this guy is admin and you are storing user data in plain text, or there is some other issue but I am surprised how he was able to pin point every planet I have with different username and email address.

**Comment by petaki** [comment]
@dfafefadfe Thank you for your report! The game has no admin role, therefore the user can only find you with the starmap API endpoint. But I will plan to add the starter protection, which will protect you from the early attacks.
