### ISSUE TITLE
Too easy expansion!

### ISSUE THREAD

**Issue by DEMENT0R** [galaxyofdrones/galaxyofdrones#37]
Already with the number of planets more than ten, the game turns into a boring routine.

I propose to add a coefficient that increases the cost of buildings, upgrades, depending on the distance from the capital (as in the Сivilization game).

The cost of maintaining drones and their upgrades are also required. Everything should be with linear growth of characteristics and exponential growth of prices.

**Comment by petaki** [comment]
Merged https://github.com/galaxyofdrones/galaxyofdrones/commit/a26f842a0b74ea8136612ee3f3f8edd6b54147e4
