### ISSUE TITLE
Sorry, the server is full :(

### ISSUE THREAD

**Issue by miladworkshop** [galaxyofdrones/galaxyofdrones#50]
hi

i install this script and after login get this Message : 

Sorry, the server is full :(

**Comment by edvordo** [comment]
That happens when [there are no available planets](https://github.com/galaxyofdrones/galaxyofdrones/blob/master/app/Http/Controllers/Web/StartController.php#L32).

Run the `starmap:generate` command (can take a long time).

**Comment by petaki** [comment]
@edvordo Thanks for the answer.
