### ISSUE TITLE
The new email verification killed the game.

### ISSUE THREAD

**Issue by ryanrca** [galaxyofdrones/galaxyofdrones#58]
Cannot login to play at `https://play.galaxyofdrones.com`.
The email verification doesn't work.  I haven't received a verification link despite trying every day for about a week.  There is nothing in the spam folder either.

This verification step should be removed.  I suggest a re-capta system instead.

**Comment by petaki** [comment]
@ryanrca Thanks for your report! We need e-mail verification because we would like to introduce some notifications for battle and other activities.

I changed the e-mail provider, can you try again?

**Comment by petaki** [comment]
Please reopen if the error still exists.
