### ISSUE TITLE
Building upgrades not getting finished

### ISSUE THREAD

**Issue by edvordo** [galaxyofdrones/galaxyofdrones#65]
I've noticed some of my building upgrades were not finished and are stuck on `remaining = 0`

Example grid IDs this has happend to

43669 - stuck at level 1 upgrade
54924 - stuck at level 8 upgrade

I cannot do anything with these, cannot demolish, cannot upgrade, they are just there, taking up space.

**Comment by edvordo** [comment]
I was able to unstuck these by deleting the upgrade from browsers' console. 

This is till an issue tho.

**Comment by petaki** [comment]
@edvordo thanks for the report, I will investigate this

**Comment by edvordo** [comment]
Now it happened when training units.

Building/Grid IDs affected 113696, 113691, 113685 all on the same planet

**Comment by edvordo** [comment]
A movement is stuck now as well at remaining = 0

Movement id: 13962
![image](https://user-images.githubusercontent.com/6738779/70928492-719fb600-2031-11ea-9127-aedc6c18d114.png)

**Comment by edvordo** [comment]
Well, just about any and all construction / training is now halted for me. 
I've got several planets with stuck training / upgrades. 

Even restarting them (making a request from console to delete upgrade / training) doesn't seem work anymore, they just get stuck again.

Only thing working for me at this point is just resource collecting.

**Comment by edvordo** [comment]
Any updates on this? :)
I get that it's holidays season and I do not mean to rush anything, just asking.

**Comment by edvordo** [comment]
Not sure what changed, but on new planets and new training/construction (on pre-owned planets) seem to be working alright now.

It's just those stuck upgrades / training I still have and can do almost nothing with (I can delete the training / cancel the upgrade and re-do it, but I'd prefer not to if it can be helped).

---
Also I think I found a new issue, some planets, even tho I have 7 Drone Bay buildings, I do not have the full capacity available to me.

For example, planet id 17505, I've got 7 Drone Bay buildings and hence should have 141k free unit supply storage (each building 20,000 unit supply giving 140k combined + 1000 unit supply from Command Center), but API responds with `133,400` available unit supply storage space. 

This value seems to be stored in the database as a table column, so I guess some Upgrade(s) of one (or more) of the Drone Bays didn't update the planet record properly.

**Comment by edvordo** [comment]
I'd welcome (say) a button to let us finish the upgrade / training manually. This could be a mechanic, that would use solarium in case the time remaining would be more than say a minute (scaled based on how many minutes are remaining possibly?), otherwise of course free.

I think even  the shortest upgrades / training are more than a minute. Also it would encourage players to harvest solarium more, since that could speed up unit production. IDK, just an idea.

But a button to manually finish an upgrade / unit training would be definitely helpful, if possible!

Also some kind of way to recalculate the (static values of a) planet would be nice, to solve the problem in my last comment. :)

**Comment by edvordo** [comment]
Welp, I (finally) gave up on this / waiting.

I've cancelled the stuck training and queued new ones. Same for the stuck building upgrades.
A bit of a loss of a momentum, but eh `¯\_(ツ)_/¯`

Also I figured out a trick to force the planet sync manually. On planets with 5 resource spots it forces me to demolish and then rebuild a building, but it's just a turret, so who cares. :)

**Comment by edvordo** [comment]
I've stumbled across another issue, similar to the one I mentioned in [#issuecomment-570081061](https://github.com/galaxyofdrones/galaxyofdrones/issues/65#issuecomment-570081061), but this time with trained units.

I believe it's because the quantity is, once again, a property / column (granted, this time I understand why, makes no sense to keep a list of individual units in database) that gets incremented and when multiple trainings get finished in quick succession, not all updates are stored fully.

I'll accept partial blame for this, since I'm creating the trainings too quickly, but still ..

**Comment by csaaro** [comment]
> A movement is stuck now as well at remaining = 0
> 
> Movement id: 13962
> ![image](https://user-images.githubusercontent.com/6738779/70928492-719fb600-2031-11ea-9127-aedc6c18d114.png)

Is there a solution for this I have several such transporters in space?

**Comment by edvordo** [comment]
Unfortuanatelly, I haven't found a way to make the transports finish. I think this has to be done on the server by @petaki
