### ISSUE TITLE
websocket setup on apache

### ISSUE THREAD

**Issue by albosmart-ro** [galaxyofdrones/galaxyofdrones#71]
How do i set my .htaccess for the webscoket to work properly in apache?

**Comment by edvordo** [comment]
I played with this some 2 year ago.
[Here](https://github.com/edvordo/notes-and-rants/blob/master/instructions/laravel-echo-server_apache2_proxypass-conf.md) is a guide I wrote for myself to make websockets run on the same domain / vhost as the project. 

Hope it helps you :)
