### ISSUE TITLE
[Bug] Fresh login and comeback to the Game not good working. 

### ISSUE THREAD

**Issue by magic-space** [galaxyofdrones/galaxyofdrones#83]
Hey community,
After install im logged in. 
Game shows very good. 
Than after 2 hours I come back zu the game, the game content is not showing. 

Only the menu is showing. 
I can't see buttons on profile menu. 

I used the docker version. 
The other version not work for me. 

When I delete the cache the game is working. 
What is wrong?

**Comment by Will2Down** [comment]
Same Issue at official server (Error 502 Bad gateway) for last 2 weeks.
IMHO no one can play atm.

**Comment by magic-space** [comment]
How to enable developer user modal
